# Dependabot dependency version checks / updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/graphicsmagick"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/graphicsmagick-sys"
    schedule:
      interval: "daily"
