name: Install graphicsmagick
inputs:
  version:
    description: GM version to install
    required: true

runs:
  using: composite
  steps:
    - name: System info
      run: cat /etc/apt/sources.list
      shell: bash

    - name: Dependencies
      shell: bash
      run: |
        sudo sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        sudo apt-get update
        sudo apt-get build-dep -y graphicsmagick
        sudo apt-get install -y llvm-dev libclang-dev clang mercurial libfreetype6-dev

    - name: Configure caching for graphicsmagick
      id: cache-graphicsmagick
      uses: actions/cache@v4
      with:
        path: /tmp/graphicsmagick
        key: ${{ runner.os }}-graphicsmagick-${{ inputs.version }}

    - name: Build GraphicsMagick
      if: steps.cache-graphicsmagick.outputs.cache-hit != 'true'
      shell: bash
      run: |
        hg clone http://hg.code.sf.net/p/graphicsmagick/code /tmp/graphicsmagick
        cd /tmp/graphicsmagick
        hg update -r ${{ inputs.version }}
        ./configure
        make -j $(nproc)

    - name: Install GraphicsMagick
      shell: bash
      working-directory: /tmp/graphicsmagick
      run: sudo make install -j $(nproc)

    - name: Info
      shell: bash
      run: |
        gm version
        echo
        GraphicsMagick-config --cppflags --ldflags --libs
