name: Install graphicsmagick
inputs:
  version:
    description: GM version to install
    required: true

runs:
  using: composite
  steps:
    - name: Configure caching for graphicsmagick
      id: cache-graphicsmagick
      uses: actions/cache@v4
      with:
        path: /home/runner/.local/
        key: v5-${{ runner.os }}-graphicsmagick-${{ inputs.version }}

    - name: Install dependencies
      shell: bash
      run: |
        set -euxo pipefail
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt-get update
        sudo apt-get build-dep -y graphicsmagick
  
    - name: Build and Install GraphicsMagick
      if: steps.cache-graphicsmagick.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euxo pipefail
        sudo apt-get install -y llvm-dev libclang-dev clang mercurial libfreetype6-dev
        hg clone http://hg.code.sf.net/p/graphicsmagick/code /tmp/graphicsmagick
        cd /tmp/graphicsmagick
        hg update -r ${{ inputs.version }}
        ./configure --prefix="$HOME/.local"
        make install -j $(nproc)

    - name: Add $HOME/.local to PATH
      shell: bash
      run: |
        echo "$HOME/.local" >> "$GITHUB_PATH"
        ldconfig -n "$HOME/.local/lib"

    - name: Info
      shell: bash
      run: |
        gm version
        echo
        GraphicsMagick-config --cppflags --ldflags --libs
        echo
        df -h
        echo
        free -h
