name: Install graphicsmagick
inputs:
  version:
    description: GM version to install
    required: true

runs:
  using: composite
  steps:
    - name: Configure caching for graphicsmagick
      id: cache-graphicsmagick
      uses: actions/cache@v4
      with:
        path: /usr/local
        key: v1-${{ runner.os }}-graphicsmagick-${{ inputs.version }}

    - name: Build and Install GraphicsMagick
      if: steps.cache-graphicsmagick.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euxo pipefail
        sudo sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        sudo apt-get update
        sudo apt-get build-dep -y graphicsmagick
        sudo apt-get install -y llvm-dev libclang-dev clang mercurial libfreetype6-dev
        hg clone http://hg.code.sf.net/p/graphicsmagick/code /tmp/graphicsmagick
        cd /tmp/graphicsmagick
        hg update -r ${{ inputs.version }}
        ./configure
        sudo make install -j $(nproc)

    - name: Info
      shell: bash
      run: |
        ldconfig -n /usr/local/lib
        gm version
        echo
        GraphicsMagick-config --cppflags --ldflags --libs
